### ISSUE TITLE
Enabling Microformats messes up my post header

### ISSUE THREAD

**Issue by jasontucker** [janboddez/indieblocks#85]
I havent had microformats enabled on your plugin and enabled it today and found that my my header on my website is broken (when viewing a single post). For testing purposes for you I've left it enabled so you can see what its doing. I'm using Bright Mode theme https://wordpress.org/themes/bright-mode/ on my site if that helps any. Toggling this setting is what breaks my site layout, I need to dig into what exactly is changing that is making the header get pushed to the right like that.

I'm running the latest code downloaded from github.

Test url:
https://jasontucker.blog/14565/yukitube-yuki-tsunodas-youtube-channel

**Comment by janboddez** [comment]
I found it, there should be a space after the `u-featured` class on your header image, I'll issue a fix asap.

At least the (other) microformats seem to be working OK: https://xray.p3k.app/parse?url=https%3A%2F%2Fjasontucker.blog%2F14565%2Fyukitube-yuki-tsunodas-youtube-channel&pretty=true

**Comment by janboddez** [comment]
Latest `main` should fix it.

If not, you could try disabling the relevant callback. Something like:
```
if ( class_exists( '\\IndieBlocks\\Theme_Mf2' ) ) {
  remove_filter( 'post_thumbnail_html', array( '\\IndieBlocks\\Theme_Mf2', 'add_thumbnail_class' ) );
}
```

**Comment by jasontucker** [comment]
Downloaded the latest and I'm getting this error on my homepage but the post page seems to be working ok.

PHP Warning:  Undefined variable $class in /sites/jasontucker.blog/files/wp-content/plugins/indieblocks-main/includes/class-theme-mf2.php on line 79

**Comment by jasontucker** [comment]
Digging a bit further here is my error log when i go to the home page and the single post page. I'm running syndicated links and indieblocks.


==> debug.log <==
[28-Apr-2023 16:05:43 UTC] PHP Fatal error:  Uncaught TypeError: explode(): Argument #2 ($string) must be of type string, array given in /sites/jasontucker.blog/files/wp-content/plugins/syndication-links/includes/class-syn-meta.php:404
Stack trace:
#0 /sites/jasontucker.blog/files/wp-content/plugins/syndication-links/includes/class-syn-meta.php(404): explode()
#1 /sites/jasontucker.blog/files/wp-content/plugins/syndication-links/includes/class-syn-meta.php(427): Syn_Meta::get_syndication_links_data()
#2 /sites/jasontucker.blog/files/wp-content/plugins/syndication-links/includes/class-syn-meta.php(496): Syn_Meta::get_syndication_links_elements()
#3 /sites/jasontucker.blog/files/wp-content/plugins/syndication-links/includes/functions.php(7): Syn_Meta::get_syndication_links()
#4 /sites/jasontucker.blog/files/wp-content/plugins/syndication-links/includes/class-syn-config.php(466): get_post_syndication_links()
#5 /sites/jasontucker.blog/files/wp-includes/class-wp-hook.php(308): Syn_Config::the_content()
#6 /sites/jasontucker.blog/files/wp-includes/plugin.php(205): WP_Hook->apply_filters()
#7 /sites/jasontucker.blog/files/wp-content/plugins/indieblocks-main/includes/class-theme-mf2.php(344): apply_filters()
#8 /sites/jasontucker.blog/files/wp-includes/class-wp-block.php(258): IndieBlocks\Theme_Mf2::render_block_core_post_content()
#9 /sites/jasontucker.blog/files/wp-includes/class-wp-block.php(244): WP_Block->render()
#10 /sites/jasontucker.blog/files/wp-includes/blocks.php(1051): WP_Block->render()
#11 /sites/jasontucker.blog/files/wp-includes/blocks.php(1089): render_block()
#12 /sites/jasontucker.blog/files/wp-includes/block-template.php(240): do_blocks()
#13 /sites/jasontucker.blog/files/wp-includes/template-canvas.php(12): get_the_block_template_html()
#14 /sites/jasontucker.blog/files/wp-includes/template-loader.php(106): include('...')
#15 /sites/jasontucker.blog/files/wp-blog-header.php(19): require_once('...')
#16 /sites/jasontucker.blog/files/index.php(17): require('...')
#17 {main}
  thrown in /sites/jasontucker.blog/files/wp-content/plugins/syndication-links/includes/class-syn-meta.php on line 404

==> access.log <==
47.151.49.241 - - [28/Apr/2023:09:05:43 -0700] "GET / HTTP/2.0" 500 2953 "https://jasontucker.blog/14565/yukitube-yuki-tsunodas-youtube-channel" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"

==> debug.log <==
[28-Apr-2023 16:05:44 UTC] PHP Warning:  Undefined variable $class in /sites/jasontucker.blog/files/wp-content/plugins/indieblocks-main/includes/class-theme-mf2.php on line 79

**Comment by jasontucker** [comment]
Looks like with syndicated links disabled I'm still getting this error in the log

==> debug.log <==
[28-Apr-2023 16:10:28 UTC] PHP Warning:  Undefined variable $class in /sites/jasontucker.blog/files/wp-content/plugins/indieblocks-main/includes/class-theme-mf2.php on line 79

**Comment by janboddez** [comment]
Thanks for catching that. The missing `$class` var I can fix.

The fatal error I have to look into, whether it's Share on Mastodon or Syndication Links itself.

**Comment by janboddez** [comment]
> The fatal error I have to look into, whether it's Share on Mastodon or Syndication Links itself.

This I can't reproduce; the compatibility checkbox seems to do what it's supposed to.

The other issue's fix I just pushed to `main`.

**Comment by janboddez** [comment]
@jasontucker That fatal error is almost certainly because of Syndication Links. It grabs a custom field and expects it to be a string but ... it's an array. See https://github.com/dshanske/syndication-links/blob/bcc607992dc03648eeac3e7781387109acf6a68a/includes/class-syn-meta.php#L402

I have to thank you again, though, looks like the filter I use in Share on Mastodon, to parse in the links, is now only valid for posts anymore: https://github.com/dshanske/syndication-links/blob/trunk/includes/class-syn-meta.php#L419
